/** Top Pakistani cities for delivery (alphabetical). */
export const PAKISTANI_CITIES = [
  'Abbottabad',
  'Attock',
  'Bahawalpur',
  'Bannu',
  'Burewala',
  'Chiniot',
  'Dera Ghazi Khan',
  'Dera Ismail Khan',
  'Faisalabad',
  'Gilgit',
  'Gojra',
  'Gujranwala',
  'Gujrat',
  'Hyderabad',
  'Islamabad',
  'Jhang',
  'Jhelum',
  'Kamoke',
  'Karachi',
  'Kasur',
  'Khanewal',
  'Kohat',
  'Lahore',
  'Larkana',
  'Mardan',
  'Mian Channu',
  'Mingora',
  'Mirpur',
  'Multan',
  'Muzaffarabad',
  'Nawabshah',
  'Okara',
  'Peshawar',
  'Quetta',
  'Rawalpindi',
  'Sahiwal',
  'Sargodha',
  'Sheikhupura',
  'Sialkot',
  'Sukkur',
  'Taxila',
  'Turbat',
  'Wah Cantonment',
  'Wazirabad',
];
